services:
  jupyter-cadquery:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/iashchak/cad-query-jupyter-docker:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./cq:/home/cq